# Introduction to PyTorch

In [ ]:
# Importing PyTorch
import torch
x = torch.empty(1)
print(x)
x = torch.empty(2,2,3)
print(x)

In [ ]:
x = torch.rand(2)
print(x)

x = torch.rand(3,3)
print(x)

In [ ]:
x = torch.zeros(3, 3)
print(x)
x = torch.ones(3, 3)
print(x)

x = torch.ones(2,2, dtype=torch.float16)
print(x)

In [ ]:
print(x.dtype)
print(x.size())

In [ ]:
x = torch.tensor([21.52, 10.33, 41,11])
print(x)

In [ ]:
z = x+y
print("Resultant Tensor\n",z)

In [ ]:
# Also element wise addition
z = torch.add(x, y)
print("Resultant Tensor\n",z)

In [ ]:
# Also element wise addition but storing in y
y.add_(x)
print("Resultant Tensor\n",y)

In [ ]:
# Arithmatic Operation

# Addition

z = x+y
z = torch.add(x, y)
y.add_(x)

# Subtraction

z = x-y
z = torch.sub(x, y)
y.sub_(x)

# Multiplication

z = x*y
z = torch.mul(x, y)
y.mul_(x)

# Division

z = x/y
z = torch.div(x, y)
y.div_(x)

#### -  Indexing `x[0]`, Slicing `x[:2]` or `x[2:]` and Fancy Indexing `x[0, [0,1,2]]` or `x[[0,1,2], 0]`

In [ ]:
x = torch.tensor([22,44,55,66,88])
print(x)

# First element
print("First element", x[0], end='\n\n')

# Last element
print("Last element", x[-1], end='\n\n')

# First two elements
print("First two elements", x[:2], end='\n\n')

# Elements after second item
print("Elements after second item", x[2:], end='\n\n')

# Last two elements
print("Last two elements", x[-2:], end='\n\n')

In [ ]:
x = [
    [1,   2,  3,  4,  5],
    [6,   7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
]
x = torch.tensor(x)
print(x)

In [ ]:
# First row
print("First row", x[0], end='\n\n')

# Last row
print("Last row", x[-1], end='\n\n')

# First column
print("First column", x[:, 0], end='\n\n')

# Last column
print("Last column", x[:, -1], end='\n\n')

In [ ]:
# First two elements at first row
print("First two elements at first row", x[0, [0,1]], end='\n\n')

# Last two elements at first row
print("Last two elements at first row", x[0, [-2,-1]], end='\n\n')

# First two elements at last row
print("First two elements at last row", x[-1, [0,1]], end='\n\n')

# Last two elements at last row
print("Last two elements at last row", x[-1, [-2,-1]], end='\n\n')

In [ ]:
x = [
    [1,   2,  3,  4,  5],
    [6,   7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
]
x = torch.tensor(x)
print(x)

In [ ]:
# First two elements at first column
print("First two elements at first column", x[[0,1], 0], end='\n\n')

# Last two elements at first column
print("Last two elements at first column", x[[-2,-1], 0], end='\n\n')

# First two elements at last column
print("First two elements at last column", x[[0,1], -1], end='\n\n')

# Last two elements at last column
print("Last two elements at last column", x[[-2,-1], -1], end='\n\n')

In [ ]:
# First two elements in first two rows
print("First two elements in first two rows\n", x[:2,[0,1]], end='\n\n')

# Last two elements in last two rows
print("Last two elements in last two rows\n", x[[0,1], -2:], end='\n\n')

# First two elements in first two columns
print("First two elements in first two columns\n", x[:2,:2], end='\n\n')

# Last two elements in last two columns
print("Last two elements in last two columns\n", x[-2:,-2:], end='\n\n')

#### - The `item()` function

In [ ]:
# Need to print a python scalar from the tensor
print("A tensor item: ", x[0,-1])
print("A scalar item: ", x[0,-1].item())

#### - The `reshape(rows, cols)` of numpy is `view(rows, cols)` in PyTorch

In [ ]:
x = torch.tensor([1,2,3,4,5,6])
x1 = x.view(2,3)
x2 = x.view(3,2)
print("2D - x1\n", x1)
print("2D - x2\n", x2)

In [ ]:
x = torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12])
print("1D - x\n", x, end='\n\n')
x1 = x.view(4,-1)
x2 = x.view(-1,6)
print("2D - x1\n", x1)
print("2D - x2\n", x2)

In [ ]:
x = torch.rand(3,3,2)
print("3D - x\n", x)

In [ ]:
x1 = x.view(9,-1)
x2 = x.view(-1,6)
print("2D - x1\n", x1)
print("2D - x2\n", x2)

In [ ]:
x3 = x.view(-1)
print("1D - x3\n", x3)

#### - Typecasting with `NumPy` and some `cuda` operations

In [ ]:
import numpy as np

In [ ]:
a = torch.ones(5)
print(a,"\n",type(a))
b = a.numpy()
print(b,"\n",type(b))

In [ ]:
a.add_(1)
print(a)
print(b)

In [ ]:
a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

In [ ]:
# Both will be changed again
a += 1
print(a)
print(b)

In [ ]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z.to('cpu')
else:
    print("Not available")

#### - For optimizing a variable or a vector or a matrix, we do `requires_grad=True` when creating it - `False` by default

In [ ]:
x = torch.ones(5, requires_grad=True)
print(x)

In [ ]:
import torch

#### - The `rand(3)` means only positive randoms while the `randn(3)` includes negative randoms too

In [ ]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-0.3389,  0.7706,  1.0508], requires_grad=True)


In [ ]:
# For addition <AddBackward>
z1 = x + 2
print(z1)

tensor([1.6611, 2.7706, 3.0508], grad_fn=<AddBackward0>)


#### - A graph is maintained when `requires_grad=True` just like the following

<img src="images/computational_graph.png" height="30%" width="30%">
<ul>

In [ ]:
# For multiplication <MulBackward>
z2 = x * x * 2
print(z2)

tensor([0.2297, 1.1875, 2.2085], grad_fn=<MulBackward0>)


In [ ]:
# For mean <MeanBackward>
z3 = z2.mean()
print(z3)

tensor(1.2086, grad_fn=<MeanBackward0>)


In [ ]:
# To calculate gradient
z3.backward() #dz1/dx
print(x.grad)

tensor([-0.4518,  1.0274,  1.4011])


#### - A short gradient calculation
<ul>
    <li>Forward Pass (Black)</li>
    <li>Backward Pass (Red)</li>
</ul>

<img src="images/simple_neuralnet.png">

In [ ]:
# Define feature, label and weight
x = torch.tensor(2.0)
w = torch.tensor(1.0, requires_grad=True)
y = torch.tensor(4.0)

In [ ]:
# The forward pass and compute loss
y_hat = w * x
loss = (y_hat - y)**2
print("y_hat: ", y_hat.item())
print("loss: ", loss.item())

y_hat:  2.0
loss:  4.0


In [ ]:
# The backward pass and gradient computation (main with local)
loss.backward()

In [ ]:
# The final weight derivative after gradient calculation
print("dL/dw: ",w.grad.item())

dL/dw:  -8.0


In [ ]:
# Update the weight with the learning rate
w = w - 0.01 * w.grad
print("New weight" ,w.item())

New weight 1.0800000429153442


In [ ]:
# For multiplication <MulBackward>
z2 = x * x * 2
print(z2)
# For mean <MeanBackward>
z3 = z2.mean()
print(z3)
# To calculate gradient
z3.backward() #dz1/dx
print(x.grad)

# Define feature, label and weight
x = torch.tensor(2.0)
w = torch.tensor(1.0, requires_grad=True)
y = torch.tensor(4.0)

# The forward pass and compute loss
y_hat = w * x
loss = (y_hat - y)**2
print("y_hat: ", y_hat.item())
print("loss: ", loss.item())import torch

#### - The `rand(3)` means only positive randoms while the `randn(3)` includes negative randoms too

x = torch.randn(3, requires_grad=True)
print(x)

# For addition <AddBackward>
z1 = x + 2
print(z1)

#### - A graph is maintained when `requires_grad=True` just like the following

<img src="images/computational_graph.png" height="30%" width="30%">
<ul>

# For multiplication <MulBackward>
z2 = x * x * 2
print(z2)

# For mean <MeanBackward>
z3 = z2.mean()
print(z3)

# To calculate gradient
z3.backward() #dz1/dx
print(x.grad)

#### - A short gradient calculation
<ul>
    <li>Forward Pass (Black)</li>
    <li>Backward Pass (Red)</li>
</ul>

<img src="images/simple_neuralnet.png">

# Define feature, label and weight
x = torch.tensor(2.0)
w = torch.tensor(1.0, requires_grad=True)
y = torch.tensor(4.0)

# The forward pass and compute loss
y_hat = w * x
loss = (y_hat - y)**2
print("y_hat: ", y_hat.item())
print("loss: ", loss.item())

# The backward pass and gradient computation (main with local)
loss.backward()

# The final weight derivative after gradient calculation
print("dL/dw: ",w.grad.item())

# Update the weight with the learning rate
w = w - 0.01 * w.grad
print("New weight" ,w.item())